apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: web-deploy                  
spec:
  replicas: 3                       
  selector:                         
    matchLabels:
      app: hello-world-pod                    
  template:
    metadata:
      labels:
        app: hello-world-pod                    
    spec:                           
      containers:
      - name: hello-world-pod
        image: gkgaurav31/node-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
