apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort
  selector:
    app: hello-world-pod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31111
    protocol: TCP
