apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    name: hello-world-pod
spec:
  containers:
  - name: hello-world-pod
    image: gkgaurav31/node-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
